### ISSUE TITLE
Provide schedule estimate for sequence annotation integration

### ISSUE THREAD

**Issue by diekhans** [BD2KGenomics/ga4gh-integration#1]
Need time frame on a sequence annotation PR

**Comment by diekhans** [comment]
please provide this asap

**Comment by macieksmuga** [comment]
Initial PR: This coming Monday. It will be a start, not a full deployable PR. That will take the next two or so weeks to develop.

**Comment by diekhans** [comment]
Excellent.  Lets plan a design review on Monday.
