### ISSUE TITLE
Continuous testing

### ISSUE THREAD

**Issue by david4096** [BD2KGenomics/ga4gh-integration#15]
The compliance and load tests could be automated. [These slides](https://docs.google.com/a/ucsc.edu/presentation/d/1_YREpgV6Dz0Ot6J7fvus6JRplLyqhV13o9gw8Zej0eA/edit?usp=sharing) describe a simple system architecture that would allow tests to be run with new github commits.

**Comment by kozbo** [comment]
This task is contained within #21, where we also have links to the actual ongoing work.  Closing this issue.
