### ISSUE TITLE
Variant call adjacency matrix

### ISSUE THREAD

**Issue by david4096** [BD2KGenomics/ga4gh-integration#16]
The 1kg call data is rich and can be analyzed for information about heredity. A simple model that would allow interesting questions to be asked would be to assemble a matrix connecting samples to other samples via the variants called against them.

Say I have a variant with three samples that received calls on both haplotypes. The first sample has the call `1|1` the second `1|1` and the third `0|1`. For this variant we are tempted to say the first two samples are nearer to each other in variant space. We might track this relationship using a data structure that connects pairs of callSetIds to list of variant IDs.

Beware potentially confusing pseudo code!

```
callMatrix = {}
for variant in searchVariants(start, stop, chrom):
    for call_inner in variant.calls
        for call_outer in variant.calls
            if call_inner.genotype[0] = call_outer.genotype[0]
                callMatrix[call_inner.id + call_outer.id].append(variant.id)
```

This example counts only when both samples agree on the first haplotype. One should extend this for the second haplotype, or when both are shared.

It is now possible to ask how related two callSetIds are by counting the number of shared variants between them (the length of the array `callMatrix[callSetId1 + callSetId2]`. For example, the two most related individuals in the data set ought to share the highest number of variants.

This data structure is offered as a suggestion. Another approach would be to make a dictionary with each callSetId mapped to every other callSetId to make questions like, "Who is the nearest relative of this participant?" easier to ask.

```
callMatrix[call_inner.id][call_outer.id].append(variant.id)
```

This is meant to be a fairly open-ended task to model relationships between the samples by looking at the call data. There are other metadata regarding subpopulation which would be interesting to include as part of this analysis.

**Comment by david4096** [comment]
@nishill has picked this up.

It may be useful during testing to compare the variant calls for related individuals (as provided by 1kgenomes).

[20140625_related_individuals.txt](https://github.com/BD2KGenomics/ga4gh-integration/files/338236/20140625_related_individuals.txt)

**Comment by kozbo** [comment]
Is this issue completed?

**Comment by nishill** [comment]
I just pushed my cleaned up version of the code to my personal bioapi-examples repo. I will issue a pull request soon and then it should be complete.
