### ISSUE TITLE
Add GA4GH API To BRCA Exchange

### ISSUE THREAD

**Issue by david4096** [BD2KGenomics/ga4gh-integration#20]
<img width="778" alt="screen shot 2016-06-29 at 11 36 12 am" src="https://cloud.githubusercontent.com/assets/3795586/16464156/b89b3162-3ded-11e6-9204-5b603f43554b.png">

[BRCA Exchange Site](http://brcaexchange.org)

[BD2KGenomics/brca-website](https://github.com/BD2KGenomics/brca-website/tree/afc7bbf9de9314d1f9c53ca7814377e8cafbeaff)

[Django](https://www.djangoproject.com/start/) - the application framework they are using

PostgreSQL is the database backend... [A little about SQL syntax](http://www.w3schools.com/sql/sql_syntax.asp)

There is an interactive SQL prompt [here](http://www.w3schools.com/sql/trysql.asp?filename=trysql_select_all) so you can try out queries without installing anything (or worrying about breaking anything).

Some notes I've put together on what needs to be done [here](https://docs.google.com/presentation/d/1-Wx67UXcpVR-GW-HC2Vus6hlK9BjV_gnnz4k1wgShr4/edit?pref=2&pli=1#slide=id.g14070ea511_0_59).

The primary pain point is that the SQL queries will be complicated by the table design, namely that splitting items into variant sets will require splitting the provider string. A string parsing technique might be needed to populate other fields of the variant messages.

**Comment by david4096** [comment]
Abraham's fork of https://github.com/achave11/brca-website

**Comment by kozbo** [comment]
can we close this now?

**Comment by david4096** [comment]
Can we leave it open until they do their next release? I still haven't been able to use a live site because of some environment problems we've had.

**Comment by kozbo** [comment]
Seems reasonable. Next merge is slated for today, so give it a try tomorrow. If OK, then close.

**Comment by david4096** [comment]
We hit a snag in the deployment... pyyaml is giving him grief for some reason! It might not affect functionality though .. https://github.com/ga4gh/ga4gh-common/issues/22

**Comment by david4096** [comment]
OK, we have what looks like a stable production GA4GH instance, not a reference server, on the BRCA exchange data! HUGE congratulations and thanks to @achave11!!! Thanks @zfisch @acthp @strbean @maryjgoldman @melissacline @diekhans @kozbo for the effort and thought you've put into this becoming a reality.

```
(env) ➜  django git:(master) ✗ http post http://brcaexchange.org/backend/data/ga4gh/v0.6.0a7/datasets/search
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Type: application/json
Date: Mon, 09 Jan 2017 22:08:30 GMT
Keep-Alive: timeout=5, max=100
Server: Apache/2.4.7 (Ubuntu)
Transfer-Encoding: chunked

{
    "datasets": [
        {
            "description": "Variants observed in brca-exchange project", 
            "id": "brca", 
            "name": "brca-exchange-variants"
        }
    ]
}
```

From the inside, it often seems like we're making sausage and it can be difficult to find a moment to reflect. Please consider, if we are correct in our assumptions of how these data will be used to improve the human condition, the types of automation, analysis, and democratization of the scientific process you all have worked to enable will be looked back on like the first book printers. The expertise of curation, the clarity of thought in the inception of the GA4GH, and the engineering effort all come together to produce something that the world has never seen before!

If you agree many of the problems facing genomics and health are in organizing and sharing results, the BRCA Exchange API presents something akin to the first brick of a software architecture that will change the way bioinformatics is done. Just like students today will laugh about going to the library for something more than a fast internet connection, they will soon say the same of files.

I look forward to the applications and analyses (and data quality bugs)! Future developments might include:

* returning `Call` data
* providing a greater variety of Variant Sets mapped to the providers
* providing a variant annotations interface (transcript effects)
* collecting API analytics
* authenticated interface (there is some authentication flow already present in the application)
* peer service (this allows the service to notify clients about other GA4GH servers)
* maintenance to remain consistent with the upstream API (it's still alpha, and we'll probably have at least 3 more alphas before going to a stable release)
