### ISSUE TITLE
Update 1kgenomes to biometadata

### ISSUE THREAD

**Issue by david4096** [BD2KGenomics/ga4gh-integration#22]
The data loader script for 1kgenomes needs to be updated to allow metadata indexed reads and variants. This involves converting the current CLI based workflow to a python script like prepare compliance data. This will make maintenance easier, removing the mix of python and shell scripts.

**Comment by david4096** [comment]
@nishill has been working on this. Currently adding reference sets, read groups (with biosample tags), and variant sets.

**Comment by david4096** [comment]
The script is pretty much done, working on integrating it now. https://github.com/nishill/server/blob/population_script/scripts/populations.py

**Comment by kozbo** [comment]
bump, I believe that this is complete now as the 1kGenomes server now has metadata.
