### ISSUE TITLE
Provide GA4GH API requirements for BRCA Exchange

### ISSUE THREAD

**Issue by diekhans** [BD2KGenomics/ga4gh-integration#5]
Provide a list of requirements for the GA4GH API to support the needs of the BRCA Exchange.  Please give functional requirements in terms of both data support and queries needed.  In other words, what do you want to do.

**Comment by kozbo** [comment]
Moving this to @david4096  to produce a design document which we can all collaborate on. It should include the goals for this integration project (can be expressed in several phases), along with some design requirements.  This document should ultimately answer the why and how of integrating BRCA Exchange with the GA4GH APIs.

**Comment by kozbo** [comment]
Here is the start of the [doc](https://docs.google.com/presentation/d/1-Wx67UXcpVR-GW-HC2Vus6hlK9BjV_gnnz4k1wgShr4/edit?pref=2&pli=1#slide=id.g14070ea511_0_59)

**Comment by haussler** [comment]
awesome that this is in progress!

**Comment by melissacline** [comment]
To turn the title of the issue around, here's a BRCA Exchange requirement for GA4GH.  We anticipate that the API endpoint will be used by organizations that want to ingest data from BRCA Exchange.  All data in BRCA Exchange comes originally from some repository or source.  It's important that in all modes of data access, we credit the original source.  So, in the API, we need some form of attribution to preserve the provenance and give credit to the original submitters.

**Comment by kozbo** [comment]
Closing this as the specification round is complete and implementation has started.  #20 picks up from there.
