### ISSUE TITLE
Move parts of protocol.py into ga4gh-schemas repo?

### ISSUE THREAD

**Issue by dcolligan** [BD2KGenomics/ga4gh-integration#53]
Rethink how `pb.py`, `protocol.py` and the `pb2` files relate to each other; there could be a better way to structure things.

Originally filed in https://github.com/dcolligan/ga4gh-schemas/issues/1

**Comment by david4096** [comment]
There are a couple of things we can include to make using the schemas alone easier, and the protocol serialization parts should be shared.

**Comment by david4096** [comment]
@dcolligan Thanks for this! We can close when the PR on [server](https://github.com/ga4gh/server/pull/1547) and [client](https://github.com/ga4gh/ga4gh-client/pull/56) are merged.

**Comment by dcolligan** [comment]
Fixed in:

https://github.com/ga4gh/schemas/pull/801
https://github.com/ga4gh/server/pull/1547
https://github.com/ga4gh/ga4gh-client/pull/56
