### ISSUE TITLE
Remove temporary ga4gh-schemas repo

### ISSUE THREAD

**Issue by dcolligan** [BD2KGenomics/ga4gh-integration#56]
Now that we have a schema release from ga4gh's schemas repo, there is no reason to keep my temporary schemas repo around anymore, correct?  https://github.com/dcolligan/ga4gh-schemas

Just making sure before I blow it away.

**Comment by david4096** [comment]
No, you can delete. Thanks for doing all that. It has already make a big difference to our development flow!

**Comment by dcolligan** [comment]
Deleted!
