### ISSUE TITLE
RTD build failure notifications

### ISSUE THREAD

**Issue by dcolligan** [BD2KGenomics/ga4gh-integration#63]
Our RTD builds have been failing for the past three weeks, and I'm not sure if anyone noticed until recently.

One way to avoid this problem in the future is to send build notification failures.  There is an option in the RTD admin for an email to be sent to someone on build failure: http://docs.readthedocs.io/en/latest/guides/build-notifications.html  I think we should enable this feature, but what email should we send the notifications to and who should watch it?

Discovered when investigating https://github.com/ga4gh/schemas/issues/819

Build failure example links:

server: https://readthedocs.org/projects/ga4gh-reference-implementation/builds/5097461/
client: https://readthedocs.org/projects/ga4gh-client/builds/5097407/
schemas: https://readthedocs.org/projects/ga4gh-schemas/builds/5051360/

**Comment by david4096** [comment]
Thanks Danny!

We could reproduce the whole conda environment in travis (I think). There is currently a badge on the repo that turns red (how I caught it).  ![badge](https://readthedocs.org/projects/ga4gh-schemas/badge/)

This looks neat, which creates github issues from emails https://github.com/sibson/ghinbox .

**Comment by dcolligan** [comment]
@kozbo for the moment, can we send the build failure notifications to your email?

**Comment by kozbo** [comment]
done.
